# Generated by Django 5.0.6 on 2024-06-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_uploadedfile_upload_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="target_column",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
