# Generated by Django 5.0.6 on 2024-06-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_uploadedfile_target_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="num_trials",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
