# Generated by Django 5.0.6 on 2024-06-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_uploadedfile_num_trials"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="model_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="target_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="train_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
